pipeline:
  test:
    image: python:${PYTHON_VERSION}
    pull: true
    commands:
      - pip install -r requirements.test.txt
      - pip install -U "Django${DJANGO_VERSION}"
      - make test

matrix:
  DJANGO_VERSION:
    - ">=3.1,<3.2"
    - ">=3.2,<3.3"
  PYTHON_VERSION:
    - 3.7
